---
title: 'Lab 1: Question 1'
author: "Your Names Here"
output: pdf_document
---

```{r load packages, echo=TRUE, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2) 
# library(tidyverse) # if you want more, but still core, toolkit
```

```{r load and clean data, echo=FALSE, warning=TRUE, message=FALSE}

```


## Importance and Context
<!-- You can (and should delete each of these comments lines in your final report) --> 
<!-- Explain why the reader should care about your research question. -->

## Description of Data
<!-- Explain how your research question is operationalized, including whether the variables you create are appropriate to study the concepts in question. --> 
<!-- What is the data like before you make any changes to it --> 
<!-- What changes do you make to the data and why? --> 
<!-- What does the data look like after you've made these changes to it --> 

## Most appropriate test 
<!-- Explain which test is the most appropriate to answer your question and why it is the most appropriate --> 
<!-- List every assumption that your test requires and evaluate it. -->

## Test, results and interpretation
<!-- What are the results of your test? --> 
<!-- What do the results of this test mean? What is the practical significance --> 
<!-- Which, if any, of the assumptions that the test requires may be violated? --> 
<!-- What are the implications of those violations? --> 
